from fastapi import FastAPI, status, HTTPException, Depends
from psycopg.rows import dict_row
import psycopg
from typing import List
import time
# Related to SQL Alchemy
from . import models, utils
from .schemas import UpdatePost, CreatePost, PostResponse, UserCreate, UserResponse
from .database import engine, SessionLocal, get_db
from sqlalchemy.orm import Session
# This line create all the models
models.Base.metadata.create_all(bind=engine)


app = FastAPI()


# Setting up Psycpg
while True:
    try:
        conn = psycopg.connect(host='localhost', dbname='fastapi',
                               user='postgres', password='Nisstome123!@#OF', row_factory=dict_row)
        cursor = conn.cursor()  # Use this to execute SQL statements
        print("db connection was successful!")
        break
    except Exception as error:  # Get the error stored in Exception and store it in variable called error to be used for our message
        print("Connecting to db failed....")
        print("Error Details: ", error)
        time.sleep(2)  # to wait a little (2 seconds) before trying again


@app.get('/')
def root():
    return "Hello Message"


# Commented this out because I no longer need it but the notes are useful
"""
@app.get('/sqlalchemy')
# Depends makes the sql alchemy a dependency
def test_posts(db: Session = Depends(get_db)):
    # This db.query is literally just a sql command in disguise (abstracting all the sql logic away)
    # the print statement of posts would produce this: SELECT posts.id AS posts_id, posts.title AS posts_title, posts.content AS posts_content, posts.published AS posts_published
    # FROM posts
    # So we don't need much understanding of SQL

    # This creates the Query - to run the Query, we need another method like .all()
    # .all is going to take the sql query generated by the db.query method on the post model
    # and run it against the db and return the results
    posts = db.query(models.Post).all()
    print(posts)
    return {"data": "succ"}
"""


@app.get('/posts', response_model=List[PostResponse])
def get_posts(db: Session = Depends(get_db)):
    posts = db.query(models.Post).all()
    return posts


@app.post('/posts', status_code=status.HTTP_201_CREATED, response_model=PostResponse)
def create_posts(post: CreatePost, db: Session = Depends(get_db)):
    # can not use f"" -> makes vulnerable for SQL injection - user can insert SQL stuff!
    # SQL library can sanitize the input for us this way!
    # Staged changes
    # cursor.execute(
    #    """INSERT INTO posts(title, content, published) VALUES(%s, %s, %s) RETURNING *""",
    #    (post.title, post.content, post.published))
    # createdPost = cursor.fetchone()
    # TO SAVE THE DATA (BECAUSE UNTIL THIS POINT THE POST IS CREATED BY NOT COMMITTTED TO DB)
    # WE HAVE TO COMM IT IT USING ONE FINAL STEP
    # conn.commit()
    new_post = models.Post(**post.model_dump())
    db.add(new_post)
    db.commit()
    db.refresh(new_post)
    return new_post


@app.get('/posts/{id}', response_model=PostResponse)
def get_post(id: int, db: Session = Depends(get_db)):
    # cursor.execute(
    #    """SELECT * FROM posts WHERE id = %s""", (id,))
    # postRetrieved = cursor.fetchone()
    # print(postRetrieved)
    # filter does what WHERE does
    # .all() is like a loop of everything - we should do first() since we know there is gonna be just one instance
    postRetrieved = db.query(models.Post).filter(models.Post.id == id).first()
    if not postRetrieved:
        raise (HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                             detail=f"post with id {id} was not found"))
    return postRetrieved


@app.delete('/posts/{id}', status_code=status.HTTP_204_NO_CONTENT)
def delete_posts(id: int, db: Session = Depends(get_db)):
    # cursor.execute("""DELETE FROM posts WHERE id = %s RETURNING *""", (id,))
    # postDeleted = cursor.fetchall()
    # print(postDeleted)
    # conn.commit()
    # No need for a return statement in FastAPI in this case since we should handle it via HTTP_204_NO_CONTENT
    post = db.query(models.Post).filter(models.Post.id == id)
    # if the query returns back anything
    if not post.first():
        raise (HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                             detail=f'Could not find post with id {id}'))
    else:
        post.delete(synchronize_session=False)
        db.commit()


@app.put('/posts/{id}', response_model=PostResponse)
# Make sure post comes in with the right schema
def update_post(id: int, post: UpdatePost, db: Session = Depends(get_db)):
    # cursor.execute(
    #    """UPDATE posts SET title = %s, content = %s, published = %s WHERE id = %s RETURNING *""",
    #    (post.title, post.content, post.published, id))
    # postUpdated = cursor.fetchone()
    post_query = db.query(models.Post).filter(models.Post.id == id)
    postUpdate = post_query.first()
    if not postUpdate:
        raise (HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                             detail=f'post with id {id} does not exist!'))
    else:
        post_query.update(post.model_dump(),
                          synchronize_session=False)
        db.commit()
        # updated_post = db.refresh(post)
        # conn.commit()
        return post_query.first()


# ------ USER STUFF -------
@app.post('/users', status_code=status.HTTP_201_CREATED, response_model=UserResponse)
def create_user(user: UserCreate, db: Session = Depends(get_db)):
    print("user created")
    # Hash password and apply
    user.password = utils.hash(user.password)
    new_user = models.User(**user.model_dump())
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    return new_user


@app.get('/users/{id}', response_model=UserResponse)
def get_user(id: int, db: Session = Depends(get_db)):
    print("lllll")
    user = db.query(models.User).filter(models.User.id == id).first()
    if not user:
        raise (HTTPException(status_code=status.HTTP_404_NOT_FOUND,
               detail=f"USER WITH ID: {id} does not exist"))
    return user
